In [ ]:
import mlflow.data
import mlflow.sklearn
from core.mlops.mlflow_aux import set_local_mlflow_tracking_uri
from mlflow.tracking import MlflowClient

tracking_uri = set_local_mlflow_tracking_uri(project_name="classificador-cbo")

model_name = "tfidf_vect"
model_version = 1
prod_name = "champion"
model_uri = (
    f"models:/{model_name}@{prod_name}"
    if prod_name
    else f"models:/{model_name}/{model_version}"
)

# Pega os detalhes da versão do modelo
client = MlflowClient()
model_details = client.get_model_version_by_alias(name=model_name, alias=prod_name)
run = mlflow.get_run(run_id=model_details.run_id)

# Carregando os dados
dataset_info = run.inputs.dataset_inputs[0].dataset
dataset_source = mlflow.data.get_source(dataset_info)
# dataset = dataset_source.load()


# Carrega o modelo em memória
tfidf_vect = mlflow.sklearn.load_model(model_uri)

In [4]:
run.data

<RunData: metrics={'preprocessing_time': 2.1030614376068115,
 'tfidf_fit_time': 0.11324238777160645}, params={}, tags={'mlflow.log-model.history': '[{"run_id": "5e93f8fd2c1341e09d9ef8c12dab5d34", '
                             '"artifact_path": "model", "utc_time_created": '
                             '"2025-04-24 22:40:07.494480", "model_uuid": '
                             '"cf1fae4f81ac479093ae3b45b1295955", "flavors": '
                             '{"python_function": {"model_path": "model.pkl", '
                             '"predict_fn": "predict", "loader_module": '
                             '"mlflow.sklearn", "python_version": "3.11.11", '
                             '"env": {"conda": "conda.yaml", "virtualenv": '
                             '"python_env.yaml"}}, "sklearn": '
                             '{"pickled_model": "model.pkl", '
                             '"sklearn_version": "1.6.1", '
                             '"serialization_format": "cloudpickle", "code": '
                             'null}}}]',
 'mlflow.runName': 'tasteful-asp-238',
 'mlflow.source.git.commit': '07f98fdd86043aa7922e1c4df9624d59cd355f26',
 'mlflow.source.name': 'src/pipe/02_creating_embedding_models.py',
 'mlflow.source.type': 'LOCAL',
 'mlflow.user': 'alecrim'}>

In [17]:
client.list_artifacts(run.info.run_id)

[<FileInfo: file_size=56525011, is_dir=False, path='df_familias_cbo.joblib'>,
 <FileInfo: file_size=None, is_dir=True, path='model'>,
 <FileInfo: file_size=1917, is_dir=False, path='preprocessador_texto.joblib'>]

In [5]:
import joblib

dataframe_path = client.download_artifacts(
    run_id=run.info.run_id, path="df_familias_cbo.joblib"
)
with open(dataframe_path, "rb") as joblib_f:
    df = joblib.load(joblib_f)

In [ ]:
# Ok, agora preciso criar os dados de treino e teste para a criação do modelo de classificação
from sklearn.metrics.pairwise import cosine_similarity

idx_
A = df.loc[2112, "embedding"]
B = df.loc[1114, "embedding"]

similarities = []
for B in df.iloc[:, -1]:
    similarities.append(cosine_similarity(X=A, Y=B).item())

In [65]:
import numpy as np

n = 10
top_n_idx = np.argpartition(similarities, -n)[-n:]
argmax = np.argmax(similarities)

# print(df.iloc[0, 1])
print(df.iloc[argmax, 1])

Profissionais de estatística e afins

In [66]:
df.iloc[top_n_idx]

,sintese,titulo,sintese_tratado,embedding
codigo,,,,
1421,"Atua na concepção, no planejamento, na organiz...","Gerentes administrativos, financeiros, de risc...",atua concepção planejamento organização desenv...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2031,Elabora projetos e desenvolve pesquisas em ciê...,Pesquisadores das ciências naturais e exatas,elabora projetos desenvolve pesquisas ciências...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2131,"Realiza pesquisas experimentais, teóricas e co...",Físicos,realiza pesquisas experimentais teóricas compu...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2030,Elabora projeto e desenvolve pesquisa científi...,Pesquisadores das ciências biológicas,elabora projeto desenvolve pesquisa científica...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2033,Planeja e desenvolve pesquisa para promoção da...,Pesquisadores das ciências da saúde,planeja desenvolve pesquisa promoção saúde col...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2035,Elabora projetos e desenvolve pesquisas em eco...,Pesquisadores das ciências sociais e humanas,elabora projetos desenvolve pesquisas economia...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2112,"Realiza a aplicação de métodos estatísticos, o...",Profissionais de estatística e afins,realiza aplicação métodos estatísticos organiz...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2111,Realiza aplicação de conhecimento da matemátic...,Profissionais da matemática,realiza aplicação conhecimento matemática cone...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2133,"Explora, monitora e analisa superfícies e inte...",Profissionais das ciências atmosféricas e espa...,explora monitora analisa superfícies interiore...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
4153,"Realiza, de forma contínua e sistemática, cole...",Trabalhadores em registros e informações em saúde,realiza forma contínua sistemática coleta ativ...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."

In [45]:
df[40:60]

,sintese,titulo,sintese_tratado,embedding
codigo,,,,
2011,Realiza estudos dos genes e da hereditariedade...,Profissionais da biotecnologia,realiza estudos genes hereditariedade aplica v...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2012,"Produz materiais de referência metrológica, a ...",Profissionais da metrologia,produz materiais referência metrológica serem ...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2021,"Pesquisa, concebe e projeta sistemas e equipam...","Engenheiros de controle e automação, engenheir...",pesquisa concebe projeta sistemas equipamentos...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2030,Elabora projeto e desenvolve pesquisa científi...,Pesquisadores das ciências biológicas,elabora projeto desenvolve pesquisa científica...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2031,Elabora projetos e desenvolve pesquisas em ciê...,Pesquisadores das ciências naturais e exatas,elabora projetos desenvolve pesquisas ciências...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2032,Planeja e executa projetos de pesquisa de enge...,Pesquisadores de engenharia e tecnologia,planeja executa projetos pesquisa engenharia m...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2033,Planeja e desenvolve pesquisa para promoção da...,Pesquisadores das ciências da saúde,planeja desenvolve pesquisa promoção saúde col...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2034,Planeja e executa projetos - de pesquisa cient...,Pesquisadores das ciências da agricultura,planeja executa projetos pesquisa científica d...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2035,Elabora projetos e desenvolve pesquisas em eco...,Pesquisadores das ciências sociais e humanas,elabora projetos desenvolve pesquisas economia...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2041,"Realiza, na Polícia Técnico-Científica, períci...",Peritos criminais e judiciais,realiza polícia técnico científica perícias cr...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2111,Realiza aplicação de conhecimento da matemátic...,Profissionais da matemática,realiza aplicação conhecimento matemática cone...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2112,"Realiza a aplicação de métodos estatísticos, o...",Profissionais de estatística e afins,realiza aplicação métodos estatísticos organiz...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2122,"Pesquisa, concebe, projeta, desenvolve, testa ...",Engenheiros em computação,pesquisa concebe projeta desenvolve testa impl...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2123,"Projeta, implanta, integra, testa e administra...",Administradores de tecnologia da informação,projeta implanta integra testa administra rede...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2124,"Planeja, projeta e implementa redes de computa...",Analistas de tecnologia da informação,planeja projeta implementa redes computadores ...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2131,"Realiza pesquisas experimentais, teóricas e co...",Físicos,realiza pesquisas experimentais teóricas compu...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2132,Realiza estudo da composição e do comportament...,Químicos,realiza estudo composição comportamento produt...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2133,"Explora, monitora e analisa superfícies e inte...",Profissionais das ciências atmosféricas e espa...,explora monitora analisa superfícies interiore...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2134,Estuda a composição e a estrutura da crosta te...,"Geólogos, oceanógrafos, geofísicos e afins",estuda composição estrutura crosta terrestre a...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
2140,"Elabora, implementa e gerencia projetos ambien...",Engenheiros ambientais e afins,elabora implementa gerencia projetos ambientai...,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."